# Generated by Django 4.2.5 on 2023-09-14 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True)),
                ('img', models.ImageField(default='static/assets/logo.png', upload_to='imgs_noticias')),
                ('fecha_carga', models.DateTimeField(auto_now=True)),
                ('fecha_noticia', models.DateField(null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True)),
                ('img', models.ImageField(default='static/assets/logo.png', upload_to='imgs_eventos')),
                ('fecha_evento', models.DateTimeField(null=True)),
                ('ubicacion', models.TextField(blank=True)),
                ('fecha_carga', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
