# Generated by Django 4.2.5 on 2023-09-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_eventos_img_alter_noticias_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='ubicacion',
            field=models.CharField(max_length=50),
        ),
    ]
