# Generated by Django 4.2.5 on 2023-09-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_eventos_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='img',
            field=models.ImageField(default='static/assets/logo.png', upload_to='imgs_eventos'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='ubicacion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='img',
            field=models.ImageField(default='static/assets/logo.png', upload_to='imgs_noticias'),
        ),
    ]
