# Generated by Django 4.2.5 on 2023-09-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_eventos_img_alter_eventos_ubicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='img',
            field=models.ImageField(null=True, upload_to='imgs_eventos'),
        ),
    ]
