# Generated by Django 4.2.5 on 2023-09-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_eventos_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='imgs_eventos/'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='imgs_noticias'),
        ),
    ]
