# Generated by Django 4.2.5 on 2023-09-21 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_eventos_img_alter_noticias_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticias',
            name='fecha_noticia',
        ),
    ]
