# Generated by Django 4.2.5 on 2023-12-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_remove_noticias_fecha_noticia'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='desc_rapida',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='noticias',
            name='desc_rapida',
            field=models.TextField(blank=True),
        ),
    ]
